// <auto-generated />
namespace frontendplay.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class LengthValidationForComments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LengthValidationForComments));
        
        string IMigrationMetadata.Id
        {
            get { return "201305012246353_LengthValidationForComments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
